"""Encryption-at-rest for sensitive secrets stored in the database.

Secrets such as Telegram session strings, API hashes and provider API keys are
encrypted before they are written to SQLite. The key comes from the ``SECRETS_KEY``
environment variable; when it is not set, encryption is a transparent no-op so the
app still runs (with a warning) and existing plaintext databases keep working.

To stay dependency-free and portable, this uses only the standard library:

* keys are separated from the master key with HKDF-SHA256 (``hashlib``);
* confidentiality comes from a keystream generated by HMAC-SHA256 in counter mode
  (HMAC is a PRF, so this is a standard stream-cipher construction) XORed with the
  plaintext, under a fresh random 128-bit nonce per message;
* integrity/authenticity comes from Encrypt-then-MAC with a separate HMAC-SHA256 key,
  verified in constant time.

Encrypted values are stored as ``enc::<base64url(nonce || ciphertext || mac)>`` so
that legacy plaintext rows (which lack the prefix) are returned unchanged and can be
re-encrypted on the next write.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import logging
import os

logger = logging.getLogger(__name__)

_PREFIX = "enc::"
_NONCE_LEN = 16
_MAC_LEN = 32  # HMAC-SHA256 digest size
_BLOCK = 32

_warned_no_key = False


def _master_key() -> bytes | None:
    raw = (os.environ.get("SECRETS_KEY") or "").strip()
    if not raw:
        return None
    return raw.encode("utf-8")


def _hkdf(master: bytes, info: bytes, length: int = 32) -> bytes:
    """Minimal HKDF-SHA256 (extract + expand) with a fixed zero salt."""
    salt = b"\x00" * hashlib.sha256().digest_size
    prk = hmac.new(salt, master, hashlib.sha256).digest()
    okm = b""
    block = b""
    counter = 1
    while len(okm) < length:
        block = hmac.new(prk, block + info + bytes([counter]), hashlib.sha256).digest()
        okm += block
        counter += 1
    return okm[:length]


def _keystream(enc_key: bytes, nonce: bytes, length: int) -> bytes:
    out = bytearray()
    counter = 0
    while len(out) < length:
        out += hmac.new(enc_key, nonce + counter.to_bytes(4, "big"), hashlib.sha256).digest()
        counter += 1
    return bytes(out[:length])


def encryption_enabled() -> bool:
    return _master_key() is not None


def encrypt(value: str | None) -> str | None:
    """Encrypt ``value`` for storage. Returns it unchanged when no key is configured
    or it is empty/already encrypted."""
    global _warned_no_key
    if value is None or value == "" or value.startswith(_PREFIX):
        return value
    master = _master_key()
    if master is None:
        if not _warned_no_key:
            logger.warning(
                "SECRETS_KEY is not set; secrets are stored UNENCRYPTED. "
                "Set SECRETS_KEY to enable encryption at rest."
            )
            _warned_no_key = True
        return value

    enc_key = _hkdf(master, b"telegram-notebook:enc")
    mac_key = _hkdf(master, b"telegram-notebook:mac")
    nonce = os.urandom(_NONCE_LEN)
    plaintext = value.encode("utf-8")
    ciphertext = bytes(a ^ b for a, b in zip(plaintext, _keystream(enc_key, nonce, len(plaintext))))
    mac = hmac.new(mac_key, nonce + ciphertext, hashlib.sha256).digest()
    token = base64.urlsafe_b64encode(nonce + ciphertext + mac).decode("ascii")
    return _PREFIX + token


def decrypt(value: str | None) -> str | None:
    """Decrypt a stored secret. Legacy plaintext (no ``enc::`` prefix) and ``None`` are
    returned unchanged. Returns ``None`` if a value is encrypted but cannot be read."""
    if value is None or not isinstance(value, str) or not value.startswith(_PREFIX):
        return value
    master = _master_key()
    if master is None:
        logger.error("Found an encrypted secret but SECRETS_KEY is not configured; cannot decrypt.")
        return None
    try:
        blob = base64.urlsafe_b64decode(value[len(_PREFIX):].encode("ascii"))
    except (ValueError, base64.binascii.Error):
        logger.error("Stored secret is not valid base64; cannot decrypt.")
        return None
    if len(blob) < _NONCE_LEN + _MAC_LEN:
        logger.error("Stored secret is too short; cannot decrypt.")
        return None

    nonce = blob[:_NONCE_LEN]
    mac = blob[-_MAC_LEN:]
    ciphertext = blob[_NONCE_LEN:-_MAC_LEN]
    mac_key = _hkdf(master, b"telegram-notebook:mac")
    expected = hmac.new(mac_key, nonce + ciphertext, hashlib.sha256).digest()
    if not hmac.compare_digest(mac, expected):
        logger.error("Stored secret failed integrity check (wrong SECRETS_KEY?); cannot decrypt.")
        return None

    enc_key = _hkdf(master, b"telegram-notebook:enc")
    plaintext = bytes(a ^ b for a, b in zip(ciphertext, _keystream(enc_key, nonce, len(ciphertext))))
    return plaintext.decode("utf-8")
